name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::287773673131:role/cloud-resume-github-actions
          aws-region: us-east-1

      - name: Sync frontend to S3
        run: aws s3 sync frontend/ s3://quentonhorton-resume-site-tf/ --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3GWKD2B2HPXTI --paths "/*"
